### ISSUE TITLE
Multiple minor release for features?

### ISSUE THREAD

**Issue by blackxored** [semantic-release/commit-analyzer-v2#5]
I'm sorry, but if since last release (1.1.0 for the sake of example) I have two commits that are prefixed with `feat` shouldn't the next version be 1.3.0 instead of 1.2.0, or I got that part of semver wrong?

**Comment by hutson** [comment]
@blackxored you only increment by one, whether it's a patch, minor, or major.

**Comment by boennemann** [comment]
as @hbetts said
